WIP #127 Slack message
mosa-architect-study/replace-kintai pull request #160
Opened 2020-01-29 14:24 UTC by y-ookubo

とりあえず作成
ディレクトリ構成や作りは暫定的、まだ修正予定
slack自体は送れるはず(herokuからは未確認、環境変数は設定済み)

2020-02-01 08:26 UTC, y-ookubo commented
とりあえずslackは送れるようになったよ

2020-02-01 08:37 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/config/SlackConfig.kt
> +        @Value("\${secret.$SLACK_MESSAGE_WEBHOOK_URL_TEST:#{null}}") private  val testUrlStr: String?,
testのURLは必要ないです〜

2020-02-01 08:38 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/domain/service/SlackService.kt
> +        val data = mapper.readValue<Slack>(jsonData)
JSONではなく単体の文字列で受け取ってしまっていいと思います！

2020-02-01 08:39 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/application/usecase/AddPaidUseCase.kt
> +        slackService.postSlackMessage(" \n新規： *" + "ユーザー名" + "*\n日時： *" + input.paidAcquisitionDate + " (" +  ")" + "  [" + input.paidTimeType + "]*\n```\n" + input.paidReason + "```")
文字列の生成はSlackService側にやらせてしまいましょう！
あと新規・変更・削除でメソッドは分けたほうが良さそうです！

2020-02-01 08:41 UTC, itskihaga commented
domain.service -> application.service でお願いします！

2020-02-01 08:46 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/domain/service/SlackService.kt
> +        restTemplate.exchange(request, String::class.java)
スラックから200以外が返ってきたらその旨をユーザーに伝えたいです！

2020-02-01 08:48 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/controller/AddPaidController.kt
> +                else -> "謎のエラーだよ"
>謎のエラーだよ
謎のエラーはthrowして欲しいです！フロントにはステータス500で返したいので！

2020-02-02 08:11 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/config/SlackConfig.kt
> +        @Value("\${secret.$SLACK_MESSAGE_WEBHOOK_URL_TEST:#{null}}") private  val testUrlStr: String?,
デリート

2020-02-02 08:11 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/domain/service/SlackService.kt
> +        val data = mapper.readValue<Slack>(jsonData)
単体文字列に変更
ローカルはプロパティファイルからの読み込みに変更

2020-02-02 08:11 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/application/usecase/AddPaidUseCase.kt
> +        slackService.postSlackMessage(" \n新規： *" + "ユーザー名" + "*\n日時： *" + input.paidAcquisitionDate + " (" +  ")" + "  [" + input.paidTimeType + "]*\n```\n" + input.paidReason + "```")
SlackServiceさんにお願いしました！

2020-02-02 08:11 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/domain/service/SlackService.kt
> +        restTemplate.exchange(request, String::class.java)
200以外はとりあえずスロー

2020-02-02 08:11 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/controller/AddPaidController.kt
> +                else -> "謎のエラーだよ"
そのまんまスロー

2020-02-02 12:57 UTC, eatski requested changes

2020-02-02 12:57 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/config/SlackConfig.kt
> +    @Bean
Beanは必要ないと思います

2020-02-02 12:57 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/config/SlackConfig.kt
> +    ) : String? {
slackMessageだと関数の意図が伝わらないのでもう少し適した命名にしていただきたいです！

2020-02-02 12:57 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/application/service/SlackService.kt
> +    fun postAddSlackMessage(input: AddPaidInputDto) {
Inputのモデルは別で定義していただきたいです！

2020-02-02 12:57 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/application/model/Slack.kt
> +        var text: String?
こちらSlackだとクラスの役割がわからないので適切な命名をお願い致します。

2020-02-02 15:02 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/config/SlackConfig.kt
> +    @Bean
Beanを消しました

2020-02-02 15:02 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/config/SlackConfig.kt
> +    ) : String? {
変更しました。

2020-02-02 15:04 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/application/model/Slack.kt
> +        var text: String?
変更しました。

2020-02-02 15:04 UTC, y-ookubo commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/application/service/SlackService.kt
> +    fun postAddSlackMessage(input: AddPaidInputDto) {
別にしたけど、、なんか違う？

2020-02-03 04:33 UTC, itskihaga commented on mosakin-backend/src/main/kotlin/com/mosa/office/kintai/application/service/SlackService.kt
> +    fun postAddSlackMessage(input: AddPaidInputDto) {
項目レベルで同じかどうかはわからないですが、存在意義が全く違うので別です！

2020-02-03 12:02 UTC, merged